//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Ap_Id { get; set; }
        public int Ap_UserId { get; set; }
        public int Ap_Service { get; set; }
        public Nullable<System.DateTime> Ap_Date { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
